### ISSUE TITLE
Syncing Yanki between computers

### ISSUE THREAD

**Issue by jonathandgall** [kitschpatrol/yanki-obsidian#23] opened 2024-10-26 07:53 UTC
Obsidian 1.7.4 (167)
Yanki 1.5.0

> [!NOTE]
> This may be a feature request if the behavior is intended.

**Context**
I use Obsidian and Anki on two different computers. As my main one wasn't available, I set up Anki connect and Yanki on the second one, and did my sync, as usual.

**Problem**
All my cards in Anki seemed to have been duplicated, and looking at the information, it is linked to the creation of a new YankiNamespace.

Is this intended behavior? 
- If not, what could I have done differently to avoid this?
- If yes, it would be great to have a way to offset this, as it would mean that migrating to a new computer would reset our repetitions.

**Comment by kitschpatrol** [comment] 2024-10-26 15:40
Hi, thanks for trying the plugin and opening an issue.

I understand why this was confusing, but everything you've described is working as designed.

Good sleuthing spotting the namespace difference. In Yanki, the namespace is basically a unique identifier that's used to determine which Anki cards it can (or can't) touch during synchronization. In the case of Yanki Obsidian, the namespace is generated from the Obsidian Vault ID — the idea being that you can have multiple Obsidian vaults with different sets of cards that you might want to sync to the same Anki collection without interference. (And in your case if you want to delete all the duplicated Anki notes, you can use the unique namespace field to do so in the Anki UI.)

Using the Vault ID instead of the vault name makes the system robust to vault name changes, but it does introduce the edge case you've described here... since every new Obsidian vault has a unique ID. (Though I'm not sure if synced vaults have the same ID. I don't use Obsidian's sync product. Are you syncing Obsidian vaults between your machines? If so, which sync system are you using?)

Theoretically, the namespace could be exposed as a field in the Yanki Obsidian plugin's advanced options, which you could then set to the same thing on both computers... but this would expose a large surface area for potential issues if your underlying notes are out of sync between machines — and I'd need to implement a namespace migration system.

I don't expect to have time to sink into supporting the above in the near future, so for now I'll probably just add a note to the readme warning about this use case.

If you're really determined to do a multi-machine sync, I'd suggest using the [Yanki CLI tool](https://github.com/kitschpatrol/yanki) directly. It lets you specify custom namespaces at will. Its documentation also [includes a deeper dive into namespaces](https://github.com/kitschpatrol/yanki?tab=readme-ov-file#namespaces).

**Comment by jonathandgall** [comment] 2024-10-26 19:54
Thank you for your swift reply—it is very appreciated.

> Though I'm not sure if synced vaults have the same ID. I don't use Obsidian's sync product. Are you syncing Obsidian vaults between your machines? If so, which sync system are you using?

I do indeed use Obsidian's own sync so I can use the same vault between my laptop, my phone, and my desktop. Yanki is installed on my laptop and my desktop.

I completely understand the reason why you used the Vault ID; this makes total sense. My hypothesis is that Obsidian developers have a similar approach in order to manage synchronization accurately.

For now, I want to keep it simple, so I will deactivate Yanki on my desktop and delete the duplicated cards. However, I do plan to renew this very laptop in a few weeks, so I expect the problem to reappear. On the bright side, it may be an opportunity to review all my cards!

Lastly, I want to take the time to sincerely thank you for the labour of love that is Yanki. In the past two decades, I went through, in order, Anki, Supermemo, Remnote, Obsidian_to_Anki, and now Yanki. The combo between Obsidian, its ecosystem, and Yanki is simply wonderful.

**Comment by kitschpatrol** [comment] 2024-10-28 14:11
Thanks for the kind words!

**Migrating to a New Laptop**

Assuming you're using AnkiWeb to store your Anki cards, I think if you move the entirety of your Obsidian vault over to the new laptop, including the [global Obsidian settings data](https://help.obsidian.md/Files+and+folders/How+Obsidian+stores+data#Global+settings), then the Obsidian vault ID shouldn't change, and your cards should continue to sync fine with Yanki. (I'd just be sure to do an AnkiWeb sync on the new laptop first.)

**Multi-machine Syncing**

I'll have to look into whether Obsidian has a persistent vault identifier across synchronized instances... or maybe it would have been better for Yanki to generate a UUID from within the plugin on a per-vault basis and assume the plugin settings file will be synced. Either way this is a bit of a dangerous / disruptive change to the existing architecture... but it's worth looking into.

I'll add a note to the readme about this for the near term, and leave this issue open since a more robust Yanki namespace generation strategy is likely needed.

**Comment by vocalunrest** [comment] 2024-11-05 01:28
I ran into the same issue—would love support for Obsidian Sync, and a disclaimer in the README would be great in the meantime.

**Comment by kitschpatrol** [comment] 2024-12-23 08:50
Closing this for now, but please reply if you run into issues and I will re-open.

**Closed by kitschpatrol** 2024-12-23 08:50 UTC
Labels: enhancement
