### ISSUE TITLE
Sync problem (同步问题)

### ISSUE THREAD

**Issue by zhuzhige123** [kitschpatrol/yanki-obsidian#25] opened 2024-11-17 15:31 UTC
你好。

首次同步正常，后续同步就出现这样的错误显示，我没做任何修改设置。
我不懂程序代码，专业术语我看不懂，不知道如何修改。
后续根据教程修改connect设置，但还是出现这个。

---

软件很喜欢。操作方便，同步效果非常棒，几乎做到了完全数据同步。

小问题：
- 从obsidian同步到anki的文档中有一些长文，居中显示的话就观感不舒服。想通过添加靠左显示的代码来呈现，可同步用的默认模板又不可修改。
- 标题识别，初次同步到anki时，微信读书同步的标题会自动识别到首字段，但后续同步时可能出现替换为元数据标题。同时它也将obsidian中微信读书插件同步文档的书名标题全部更改为元数据三个字。
- 同步文档内时间戳视频笔记截图稍多时，图片则不显示，显示为图片的链接。

![image](https://github.com/user-attachments/assets/2664ea00-6750-4eb5-be77-364aa011384b)
![image](https://github.com/user-attachments/assets/a02e4612-d182-4550-96f1-a53a23f96dfb)
![image](https://github.com/user-attachments/assets/63e8cfc9-1b37-4963-982c-9ec6d9a0ea83)
![image](https://github.com/user-attachments/assets/2f8ddc2d-56f9-4ea5-a03d-6ef2b71e4ed1)
![image](https://github.com/user-attachments/assets/4a60a6b3-4693-4cb6-8194-d5fc2674b633)

**Comment by kitschpatrol** [comment] 2024-11-17 17:58
Machine translation of the above:

> Hello.
> The first sync works normally, but subsequent syncs show this error, and I haven't modified any settings. I don't understand programming code or technical terms, so I don't know how to fix it. I later modified the connect settings according to the tutorial, but this still occurs.
> 
> I really like the software. It's easy to operate, and the sync effect is excellent, achieving almost complete data synchronization.
> 
> Minor issues:
> * Some long texts from Obsidian synced to Anki are center-aligned, which isn't visually comfortable. I want to add code for left alignment, but the default template used for syncing can't be modified.
> * Regarding title recognition, during the initial sync to Anki, WeChat Reading's synced titles are automatically recognized in the first field, but in subsequent syncs, they might be replaced with metadata titles. At the same time, it also changes all book title headers in Obsidian's WeChat Reading plugin synced documents to the word "metadata."
> * When syncing documents with timestamps and multiple video note screenshots, the images don't display and instead show up as image links.

很抱歉，我不会说中文。请您自行翻译以下内容。

Thank you for opening an issue and for using the plugin. I'll try to address your questions as best as I can understand them through machine translation:

### Synchronization issues

I can't quite understand what might be causing this from your description, and I haven't seen this particular error come up before. Can you please share a minimal Obsidian vault / set of markdown notes that reproduces the issue?

The nature of the error message points to only a few points in the source code, one related to [tag equality checks](https://github.com/kitschpatrol/yanki/blob/main/src/lib/utilities/anki-connect.ts#L265-L279) and the other related to [loading local note files](https://github.com/kitschpatrol/yanki/blob/main/src/lib/actions/load-local-notes.ts#L36-L92).


###  Minor issues

#### Center alignment

Yanki Obsidian uses the default Anki CSS stylesheet, which is why you're seeing the centered text. The CLI version of Yanki provides a [style](https://github.com/kitschpatrol/yanki?tab=readme-ov-file#subcommand-yanki-style) command to manage custom style sheets, but this functionality is not currently exposed in the UI provided in Yanki Obsidian. I'm planning to add support for custom CSS in a future version of Yanki Obsidian. If you really want this functionality now, you could look into using the CLI version directly.

#### Title recognition

I'm not quite clear on this, if you can provide a sample note reproducing the issue that would help. do you have [automatic note names](https://github.com/kitschpatrol/yanki-obsidian?tab=readme-ov-file#automatic-note-name-settings) enabled?

#### Attachments

Have you confirmed that this is related to timestamps? Not all file types can be synced and played back in Anki, in these cases Yanki will fall back to a link. Again if you can provide an example note and asset I can take a look! Also note that the [Sync media assets](https://github.com/kitschpatrol/yanki-obsidian?tab=readme-ov-file#sync-media-assets) settings will affect how linked assets are handled.

**Comment by zhuzhige123** [comment] 2024-11-18 07:52
你好，非常感谢你的回复。我的英文不好，不好用翻译软件发给你，担心有语法相关的错误。你可以使用翻译软件阅读。

### 同步出错问题


- 终于找到了，通过文件夹和文档一个个来排除，检验，最终确认是这个文档导致的，我也不知道为什么。
- 把这个文档移动到任意文件夹中，初次同步有效，后续就会出现错误。删除该文档又可以同步。
---

[《春雪》.md](https://github.com/user-attachments/files/17796058/default.md)
- 春雪附件：![9B5F2E26BCC82AC75692F604989079C9](https://github.com/user-attachments/assets/859ad5bb-291a-4aa3-8423-0295ea749f4c)
---

### 图片不显示问题
- 有些文档中的图片不显示，与格式，时间戳和文档无关，相同的图片文件在不同的文档中，有的显示，有的不显示。把不显示的图片插入到可显示图片的文档中，却可以显示出来。
应该是同步问题。

### CLI版本
- 抱歉，我没有程序编程相关的知识，若是复杂，我可能不知道怎么使用它。我期待后续yanki的更新。
---
### 增加小功能
- 希望在后续的yanki同步中添加同步进度状态的显示。
- 
- ![image](https://github.com/user-attachments/assets/d80df41a-2d19-4fef-9b71-979fcb64a012)
![image](https://github.com/user-attachments/assets/d48afde7-2b14-49c0-8133-82a4cd130c49)

**Comment by zhuzhige123** [comment] 2024-11-18 10:52
@kitschpatrol 
你好，非常感谢你的回复。我的英文不好，不好用翻译软件发给你，担心有语法相关的错误。你可以使用翻译软件阅读。

### 同步出错问题


- 终于找到了，通过文件夹和文档一个个来排除，检验，最终确认是这个文档导致的，我也不知道为什么。
- 把这个文档移动到任意文件夹中，初次同步有效，后续就会出现错误。删除该文档又可以同步。
---

[《春雪》.md](https://github.com/user-attachments/files/17796058/default.md)
- 春雪附件：![9B5F2E26BCC82AC75692F604989079C9](https://github.com/user-attachments/assets/859ad5bb-291a-4aa3-8423-0295ea749f4c)
---

### 图片不显示问题
- 有些文档中的图片不显示，与格式，时间戳和文档无关，相同的图片文件在不同的文档中，有的显示，有的不显示。把不显示的图片插入到可显示图片的文档中，却可以显示出来。
应该是同步问题。

### 重命名问题
- 确认是微信读书插件同步时会激活yanki的重命名功能。

### CLI版本
- 抱歉，我没有程序编程相关的知识，若是复杂，我可能不知道怎么使用它。我期待后续yanki的更新。
---
### 希望增加小功能
- 希望在后续的yanki同步中添加同步百分比进度状态的显示。目前是完成后的情况。
- 导出同步时基于标签过滤掉某些不太重要的obsidian文档。
- ![image](https://github.com/user-attachments/assets/d80df41a-2d19-4fef-9b71-979fcb64a012)
![image](https://github.com/user-attachments/assets/d48afde7-2b14-49c0-8133-82a4cd130c49)

**Comment by zhuzhige123** [comment] 2024-11-19 03:50
@kitschpatrol 




"Hello. The mnemonic 'double the number of cards' has been executed --- times. However, after repeated testing by me, it did not cut the card into two. Additionally, I would like to inquire if there will be customizable fill-in-the-blank marker symbols in future updates? Because when I use Markdown, highlight and bold markup languages are used more frequently, and I would like to use them together with the cloze fill-in-the-blank marker symbols."



[自学大全（掀起日本自学狂潮！送给所有不想放弃学习的人55个自学方法！雄踞日本各大畅销书榜！自学百科全书！买回家管用一辈子）.md](https://github.com/user-attachments/files/17808909/55.md)

![image](https://github.com/user-attachments/assets/e789f3a5-1f98-4469-9677-fb55cd15e94f)

![image](https://github.com/user-attachments/assets/dc546fe3-7c05-4408-be0a-ce0abd566aec)
![image](https://github.com/user-attachments/assets/50d7e54f-1faf-45c7-9195-59225d722ace)

**Comment by kitschpatrol** [comment] 2024-11-19 05:59
Thanks for the suggestion — there will not be an option to customize the syntax. This would be complex to implement, and the plugin already has too many options.

This is one of the tradeoffs of overloading Markdown syntax to represent Anki constructs instead of using raw Anki-style markup.

This approach works well when you're you're writing cards specifically in Markdown with Yanki in mind, but isn't going to work well if you're syncing a large collection of existing Markdown notes.

If you need more customizable behavior, you might want take a look at some of the [other Obsidian Anki plugins](https://github.com/kitschpatrol/yanki-obsidian?tab=readme-ov-file#other-obsidian-anki-plugins) which offer different sets of tradeoffs from Yanki.

**Comment by zhuzhige123** [comment] 2024-11-19 06:09
@kitschpatrol 
Hello. Not much is needed; just add an option in Yanki to convert the fragments that need to be filled in by replacing the strikethrough with highlighting. Because the strikethrough is not commonly used, it is suitable for Yanki but not for daily annotation, including exporting to other file formats.

**Comment by kitschpatrol** [comment] 2024-11-19 07:40
I've provided a fix for the `TypeError: e.entries is not a function or its return value is not iterable` issue in the latest version of the plugin,  [1.5.1](https://github.com/kitschpatrol/yanki-obsidian/releases/tag/1.5.1). Thank you for providing a reproducible example. (It was related to the tag in the YAML frontmatter being a single word instead of an array of tags. The plugin has been updated to support single tags.)

Regarding your other comments:

### Tag-based synchronization filtering

> Export synchronization filters out some less important obsidian documents based on tags

This has come up before, please see the discussion in #16.

### Sync progress

> I want to add a display of the sync percentage progress status in the subsequent Yanki sync. It is currently the situation after completion."

I'd welcome a PR with this functionality, but don't have time to implement it right now. (It would be fiddly to implement since Obsidian's plugin API doesn't provide an abstraction for showing progress in the pop-up notices.)

### Strikethrough vs. Highlight for cloze deletions

Strikethrough was chosen for cloze deletions specifically because it is semantically consistent with the concept of a cloze (since it resembles redaction), and also specifically because it's not commonly used, making it less likely to be accidentally invoked with typical markup.

If might not sound like much is needed to implement what you've suggested, but there's some technical complexity involved behind the scenes, and I don't want to add options that complicate an (already complicated) part of the plugin's behavior.

If you think otherwise, you are welcome to fork the plugin and implement any options or customizations you'd like. The note type detection code is [here](https://github.com/kitschpatrol/yanki/blob/main/src/lib/parse/remark-utilities.ts#L273-L328), and most of the parsing process happens [here](https://github.com/kitschpatrol/yanki/blob/main/src/lib/parse/parse.ts#L50-L271).

### Picture not showing problem / attachments

I'm interested in this issue but I can't reproduce it with the information provided. Please open a separate issue and provide a test vault if you'd like me to take a look.

---

I'm closing this issue thread since the synchronization error was the only problem I was able to reproduce from the information provided. Typically, it's helpful to have a single issue for a single bug or feature request, so please feel free to open multiple individual issues each focused on a single topic in the future.

**Closed by kitschpatrol** 2024-11-19 07:40 UTC
Labels: bug
