### ISSUE TITLE
Incorrect handling of space-containing filenames in Obsidian URL

### ISSUE THREAD

**Issue by orca131** [kitschpatrol/yanki-obsidian#19] opened 2024-09-23 18:55 UTC
When the Yanki plugin (v1.5.0) tries to open a link with spaces in the filename (e.g. "Link with spaces"), the plugin incorrectly tries to open a file named with only the first word ("Link").

Steps to Reproduce:

1. Create two notes (e.g., "Link with spaces" and "Link-without-spaces")
2. Add identical content to both cards
3. Run the "Yanki: Sync flashcard notes to Anki" command
4. Start reviewing the new card deck in Anki
5. Click on the "Link with spaces"

Expected behavior:

- Upon clicking "Link with spaces", Obsidian should open and display the file named "Link with spaces"
- The file should be opened correctly without any errors

Actual result:

- Obsidian opens correctly
- The file named "Link with spaces" does not open
- Obsidian tries to open file named "Link" instead
- An error message appears:

![Screenshot from 2024-09-23 20-35-06](https://github.com/user-attachments/assets/75466749-969a-427a-bb80-c3494b2fb47e)

Note template:

```md
## Link with spaces

- [Link with spaces](Link%20with%20spaces.md)
- [[Link with spaces]]
- [Link with spaces](Link%20with%20spaces.md#Link%20with%20spaces)
- [[Link with spaces#Link with spaces]]
- [[Link with spaces#Link with spaces|dodo]]
- [dodo](Link%20with%20spaces.md#Link%20with%20spaces)
- [Link with spaces](<Link with spaces.md>)

## Link-without-spaces

- [Link-without-spaces](Link-without-spaces.md)
- [[Link-without-spaces]]
- [Link-without-spaces](Link-without-spaces.md#Link-without-spaces)
- [[Link-without-spaces#Link-without-spaces]]
- [[Link-without-spaces#Link-without-spaces|carl]]
- [carl](Link-without-spaces.md#Link-without-spaces)
- [Link-without-spaces](<Link-without-spaces.md>)
```

Environment:

- OS: Fedora 40
- GNOME Version: 46.5
- Obsidian Version: 1.6.7
- Installation Method: Flatpak

**Comment by kitschpatrol** [comment] 2024-09-23 19:14
Thanks, I should be able to sort this out later this week.

**Comment by kitschpatrol** [comment] 2024-09-25 04:47
Hi again, thanks for the very thorough reproduction instructions but unfortunately I couldn't reproduce the issue on either macOS or Ubuntu.

For a vault with the following hierarchy, with the notes containing the example Markdown you provided:

```
📂 Anki
└── 📂 Test
    └── 📂 More test
        ├── 📝 Link with spaces.md
        └── 📝 Link-without-spaces.md
```

Clicking any "Link with space" in the resulting Anki cards resolves to the correct note in Obsidian.

![Screenshot 2024-09-25 at 00 36 35 of Obsidian - Link with spaces - Vault - Obsidian v1 6 7@2x](https://github.com/user-attachments/assets/5b1f9bb7-c821-49b9-8c39-9575c7eaf698)

The generated card HTML shows that spaces are correctly escaped:

```html
<!-- This HTML was generated by Yanki, a Markdown to Anki converter. Do not edit directly. -->
<div class="yanki namespace-yanki-obsidian-vault-id-6952605afeff25ac front model-yanki-basic">
<h2>Link with spaces</h2>
<ul>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md" data-yanki-src-original="Link%20with%20spaces.md">Link with spaces</a></li>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md" data-yanki-src-original="Link%20with%20spaces">Link with spaces</a></li>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md%23Link%20with%20spaces" data-yanki-src-original="Link%20with%20spaces.md#Link%20with%20spaces">Link with spaces</a></li>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md%23Link%20with%20spaces" data-yanki-src-original="Link%20with%20spaces#Link%20with%20spaces">Link with spaces</a></li>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md%23Link%20with%20spaces" data-yanki-src-original="Link%20with%20spaces#Link%20with%20spaces">dodo</a></li>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md%23Link%20with%20spaces" data-yanki-src-original="Link%20with%20spaces.md#Link%20with%20spaces">dodo</a></li>
  <li><a href="obsidian://open?vault=Vault&amp;file=%2FAnki%2FTest%2FMore%20test%2FLink%20with%20spaces.md" data-yanki-src-original="Link with spaces.md">Link with spaces</a></li>
</ul>
</div>
```

Is there anything else unique about your configuration? Are you willing to share the most minimal Obsidian vault that triggers the issue on your end?

**Comment by kitschpatrol** [comment] 2024-09-30 03:11
Closing since I can't reproduce this issue as demonstrated above.

Please reopen if you can provide more details on your specific vault configuration and how best to reproduce. Thank you.

**Closed by kitschpatrol** 2024-09-30 03:11 UTC
Labels: bug
