### ISSUE TITLE
Images in custom attachment folder don't work

### ISSUE THREAD

**Issue by xelaras** [kitschpatrol/yanki-obsidian#3] opened 2024-07-21 05:40 UTC
My attachments are in the following folder: \300 Conoscenza\390 allegati

If I reference an image from that folder, I get the following error:
![image](https://github.com/user-attachments/assets/799e78db-4b80-496e-9f14-54287a8e85cc)

I get the same error if I move the image into another folder.

If I however put the image in the vault root folder, it works.

**Comment by kitschpatrol** [comment] 2024-07-21 15:38
I've been able to reproduce this, I actually didn't realize that Obsidian will let you embed an attachment from outside of the designated attachments folder *without* a relative path. Seems a little freewheeling. 😅

Here's my test configuration:

Obsidian vault structure:
```
 'Yanki Issue 3'
├──  '300 Conoscenza'
│  └──  '390 allegati'
│     └──  wop-agenda.jpg
├──  Anki
│  └──  Test.md
└──  wop-agenda-root.jpg
```

`Test.md` Markdown:
```md
Non-relative attachment from the vault folder `\300 Conoscenza\390 allegati`:

![[wop-agenda.jpg]]

---

Attachment from the vault root:

![[wop-agenda-root.jpg]]
```

Both of the images render correctly in Obsidian, but Yanki is failing to resolve `![[wop-agenda.jpg]]` during the export process because it can't figure out its path.

I'm looking into how to fix this, in the meantime changing your embed code to a relative path like below should allow syncing to Anki:

```md
![[../300 Conoscenza/390 allegati/wop-agenda.jpg]]
```

**Comment by kitschpatrol** [comment] 2024-07-22 17:50
Quick update:

I dug into this issue a bit further, and due to the [ambiguities](https://forum.obsidian.md/t/add-settings-to-control-link-resolution-mode/69560) around links in Obsidian vs. links in standard Markdown, the fix is going to be a bit more involved than I anticipated.

There are [APIs inside Obsidian](https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFirstLinkpathDest) that can handle this, but I'm going to need to reimplement them for consistency with the stand-alone [yanki CLI tool and library](https://github.com/kitschpatrol/yanki).

So, for now please use the relative link fix described above, or consider a Plugin like [consistent-attachments-and-links](https://github.com/dy-sh/obsidian-consistent-attachments-and-links) which can automate good relative link hygiene.

I'll keep this issue open and update it when a more permanent fix is available.

**Comment by jakeoung** [comment] 2024-07-30 03:18
It would be great if there is an option to generate anki notes even if there is an attachment error.

**Comment by kitschpatrol** [comment] 2024-07-30 04:45
Agreed, an update with a fix is coming very soon.

**Comment by kitschpatrol** [comment] 2024-08-01 05:33
@jakeoung @xelaras A fix for this plus some other improvements are in the just-release [version 1.1.0](https://github.com/kitschpatrol/yanki-obsidian/releases/tag/1.1.0).

Thanks for your patience and please let me know if this resolves the issues on your side.

**Comment by kitschpatrol** [comment] 2024-08-06 16:28
Closing this since it appears to be resolved in the latest version. Please reopen if necessary.

**Closed by kitschpatrol** 2024-08-06 16:28 UTC
Labels: bug
