### ISSUE TITLE
Sync error: cannot create note for unknown reason

### ISSUE THREAD

**Issue by ssslinppp** [kitschpatrol/yanki-obsidian#1] opened 2024-07-16 11:05 UTC
![image](https://github.com/user-attachments/assets/9cd41f78-d459-4043-ab58-3d13e5cb328e)

![image](https://github.com/user-attachments/assets/129436bf-5d89-44c8-9300-b94a9746fd5d)
![image](https://github.com/user-attachments/assets/76264fe2-d73b-4bda-9adc-1bbf87ba18c4)
![image](https://github.com/user-attachments/assets/04a56724-71e8-45b8-b05d-dd116a348dbf)

**Comment by kitschpatrol** [comment] 2024-07-16 13:49
Thanks, this error comes from inside Anki-Connect, so your configuration is probably fine, it's more likely an issue parsing your notes' markdown.

Does syncing only a single, very simple note, like below, work?

```
front of the card

---

back of the card
```

**Comment by kitschpatrol** [comment] 2024-07-16 15:04
Also @ssslinppp , if you're comfortable sharing your 42 Markdown Anki note files (or narrowing it down to the one that fails to sync and sharing that one), that would really help me reproduce this.

In the meantime I'm looking into adding some additional logging.

**Comment by dscherdi** [comment] 2024-07-29 04:23
I needed to add the yanki note types in anki manually to get it working
![image](https://github.com/user-attachments/assets/371575c6-cf6e-4614-9f20-3fab7617fd90)

**Comment by kitschpatrol** [comment] 2024-07-29 05:28
That's interesting, the plugin should create those automatically as needed. I'll test again.

**Comment by kitschpatrol** [comment] 2024-07-29 05:55
Hi @dscherdi, I just ran through the Obsidian + Anki + Yanki plugin installation steps from scratch on a fresh macOS VM, and confirmed that Anki note types are being created correctly on-demand, at least on "my machine":

![Screenshot 2024-07-29 at 01 51 32 of VirtualBuddy@2x](https://github.com/user-attachments/assets/174fbd0c-37c1-444b-bf53-eea4503a8da5)

(In the above case only the `Yanki - Basic` type, since I'm syncing a single note.)

Creating the Yanki-specific note types manually shouldn't be required, and can be tricky since they need specific fields.

Can you please share some details about your Anki version, platform, etc. and so I can try to reproduce this?

**Comment by dscherdi** [comment] 2024-07-29 06:39
The Yanki - Basic is created, but not the other ones, so you Cloze notes dont work for example

**Comment by kitschpatrol** [comment] 2024-07-29 06:49
Just tested and cloze note types are being automatically created just fine as well:

![Screenshot 2024-07-29 at 02 45 15 of VirtualBuddy - @2x](https://github.com/user-attachments/assets/9853a768-4deb-4afb-bf26-55e0059452f2)

Can you provide an example of a note in Obsidian that you're expecting to become a cloze? Does it have `~~strikethrough~~` syntax?

For example:
```md

This is a ~~cloze~~

```

The [readme](https://github.com/kitschpatrol/yanki-obsidian?tab=readme-ov-file#markdown-note-types) explains in detail how note types are automatically inferred (and then automatically created as necessary in Anki) based on the structure of your Markdown.

**Comment by kitschpatrol** [comment] 2024-08-01 05:48
I'm closing this thread since I don't have the information necessary to reproduce either issue.

@ssslinppp If you can share the simplest markdown files that trips the error you're seeing, I'm happy to reopen and look into it.

@dscherdi Similarly, I can't reproduce this, but if you want to provide more information please open a separate issue, since it's different from OP's issue.

Regardless, I suggest taking a look at the [most recent version](https://github.com/kitschpatrol/yanki-obsidian/releases/latest) of the plugin to see if it helps.

**Closed** 2024-08-01 05:49 UTC
Labels: bug
